sudo: required
services:
  - docker

before_install:
  - docker build -t jreyes4/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jreyes4/react-test npm test

after_success:
  - docker build -t jreyes4/multi-client ./client
  - docker build -t jreyes4/multi-nginx ./nginx
  - docker build -t jreyes4/multi-server ./server
  - docker build -t jreyes4/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push jreyes4/multi-client
  - docker push jreyes4/multi-nginx
  - docker push jreyes4/multi-server
  - docker push jreyes4/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-068598347499
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

